# Database
spring.datasource.url=jdbc:mysql://localhost:3306/shoppingverse
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

# Mail
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD

# JWT
jwt.secret=YOUR_SECRET_KEY